version: "3"
services:
  poll:
    build: ./poll
    restart: on-failure
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - poll-tier
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  redis:
    image: "redis"
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - back-tier
      - poll-tier
  worker:
    build: ./worker
    restart: on-failure
    depends_on:
      - redis
      - db
    networks:
      - back-tier
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
  db:
    image: "postgres:9.4"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - back-tier
      - result-tier
  result:
    build: ./result
    restart: on-failure
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: